Add ResponseErrorHandler to handle REST calls
scoperetail-io/fusion-core pull request #4
Opened 2021-06-15 00:16 UTC by javierscope

2021-06-15 09:56 UTC, amit-petkar requested changes
Need changes.

2021-06-15 09:56 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +	public void handleError(URI url, HttpMethod method, ClientHttpResponse response) throws IOException {
if (httpResponse.getStatusCode()
          .series() == HttpStatus.Series.SERVER_ERROR) {
             // log its a server error 
        } else if (httpResponse.getStatusCode()
          .series() == HttpStatus.Series.CLIENT_ERROR) {
             // log its client error
            if (httpResponse.getStatusCode() == HttpStatus.NOT_FOUND) {
                // log not found error
                throw new NotFoundException();
            }
        }

2021-06-15 09:56 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +		Scanner s = new Scanner(inputStream).useDelimiter("\\A");
Aren't we printing entire failed response body?

2021-06-15 09:56 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +public class CustomResponseErrorHandler implements ResponseErrorHandler {
Rename to GenericRestResponseErrorHandler

2021-06-15 09:56 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +	public boolean hasError(ClientHttpResponse clientHttpResponse) throws IOException {
Add test cases around this

2021-06-15 09:56 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/adapter/out/web/http/impl/PosterOutboundHttpAdapterImpl.java
>      final RestTemplate restTemplate = new RestTemplate(clientHttpRequestFactory);
Also add ClientHttpRequestInterceptor - to log the request details before sending the request

2021-06-15 15:15 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/adapter/out/web/http/impl/PosterOutboundHttpAdapterImpl.java
>      final RestTemplate restTemplate = new RestTemplate(clientHttpRequestFactory);
We are already printing the requests, do we still need the Interceptor?

2021-06-15 16:09 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +public class CustomResponseErrorHandler implements ResponseErrorHandler {
Ok

2021-06-15 16:17 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +	public void handleError(URI url, HttpMethod method, ClientHttpResponse response) throws IOException {
Ok

2021-06-15 16:22 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/CustomResponseErrorHandler.java
> +		Scanner s = new Scanner(inputStream).useDelimiter("\\A");
Yes

2021-06-16 15:16 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/adapter/out/web/http/impl/PosterOutboundHttpAdapterImpl.java
>      final RestTemplate restTemplate = new RestTemplate(clientHttpRequestFactory);
Loggin interceptor added

2021-06-30 08:53 UTC, amit-petkar requested changes
Need chages.

2021-06-30 08:53 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/GenericRestResponseErrorHandler.java
> +public class GenericRestResponseErrorHandler implements ResponseErrorHandler {
Spring already has DefaultResponseErrorHandler. Are we doing anything different?

2021-06-30 08:53 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/GenericRestResponseErrorHandler.java
> +		Scanner s = new Scanner(inputStream).useDelimiter("\\A");
Why just a single line?

2021-06-30 08:53 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/GenericRestResponseErrorHandler.java
> +	static class CustomException extends IOException {
Any specific need to create custom exception?

2021-06-30 08:53 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/LoggingInterceptor.java
> +	public ClientHttpResponse intercept(HttpRequest req, byte[] reqBody, ClientHttpRequestExecution ex)
https://howtodoinjava.com/spring-boot2/resttemplate/clienthttprequestinterceptor/

2021-07-02 14:01 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/GenericRestResponseErrorHandler.java
> +		Scanner s = new Scanner(inputStream).useDelimiter("\\A");
This is reading all the message

2021-07-02 15:31 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/LoggingInterceptor.java
> +	public ClientHttpResponse intercept(HttpRequest req, byte[] reqBody, ClientHttpRequestExecution ex)
logging request and response as per comment

2021-07-02 18:04 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/GenericRestResponseErrorHandler.java
> +public class GenericRestResponseErrorHandler implements ResponseErrorHandler {
using default handler

2021-07-02 18:05 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/common/GenericRestResponseErrorHandler.java
> +	static class CustomException extends IOException {
custom exception removed

2021-07-05 10:24 UTC, amit-petkar requested changes
need changes.

2021-07-05 10:24 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/common/LoggingInterceptor.java
> +		response.getHeaders().add("headerName", "VALUE");
???

2021-07-05 16:10 UTC, amit-petkar approved these changes
Approved.

2021-07-05 17:05 UTC, merged