MCS-3968 Hashkey FTL for log creation
scoperetail-io/fusion-core pull request #8
Opened 2021-06-17 16:01 UTC by javierscope

2021-06-20 08:03 UTC, amit-petkar requested changes
Need discussion

2021-06-20 08:03 UTC, amit-petkar commented on src/main/java/com/scoperetail/fusion/core/application/service/command/PosterService.java
> +            return domainToDomainEventJsonFtlTransformer.getHashKey(event, paramsMap, adapter.getTemplate());
Need discussion. Can we directly get the hashkey without going through the usecases?

2021-06-22 11:05 UTC, ravi-zadpide requested changes

2021-06-22 11:05 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/fusion/core/application/service/transform/impl/DuplicateFtlTransformer.java
> +public class DuplicateFtlTransformer extends DuplicateTransformer {
Rename to HashKeyFtlTemplateTransformer

2021-06-22 11:05 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/fusion/core/application/service/transform/impl/DuplicateTransformer.java
> +public class DuplicateTransformer extends AbstractTransformer {
make this abstract and Rename to AbstractHashKeyTemplateTransformer

2021-06-22 11:05 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/fusion/core/application/service/transform/impl/DuplicateVelocityTransformer.java
> +public class DuplicateVelocityTransformer extends DuplicateTransformer {
Rename to HashKeyVelocityTemplateTransformer

2021-06-22 13:25 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/adapter/in/web/command/AbstractBaseDelegate.java
> +  private static final String TEMPLATE_NAME = "hash_key";
fixed

2021-06-22 13:25 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/adapter/in/web/BaseDelegate.java
> +public interface BaseDelegate {
renamed

2021-06-22 13:25 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/adapter/in/web/command/BaseDelegateService.java
> +public class BaseDelegateService implements BaseDelegate {
renamed

2021-06-22 13:29 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/application/service/transform/impl/DuplicateFtlTransformer.java
> +public class DuplicateFtlTransformer extends DuplicateTransformer {
renamed

2021-06-22 13:31 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/application/service/transform/impl/DuplicateVelocityTransformer.java
> +public class DuplicateVelocityTransformer extends DuplicateTransformer {
renamed

2021-06-22 14:06 UTC, javierscope commented on src/main/java/com/scoperetail/fusion/core/adapter/in/web/command/BaseDelegateService.java
> +		 if (useCase.isPresent() && useCase.get().getDedupeCheck()) {
done

2021-06-24 15:51 UTC, amit-petkar approved these changes
Approved.

2021-06-24 20:32 UTC, merged